spring.application.name=doctorcare
server.port=8085

# --- CLOUD DATABASE (MongoDB Atlas) ---
spring.data.mongodb.uri=mongodb+srv://koushik:Koushik%4012345@cluster0.1uybnt3.mongodb.net/doctor_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=doctor_db

# Security Key for JWT
jwt.secret=FouriseDoctorAppSuperSecretKeyForSecurityDoNotShare