spring.application.name=doctorcare
# Changing the port so Eclipse cannot steal our requests!
server.port=8085

# Bulletproof MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/doctor_db
spring.data.mongodb.database=doctor_db

# Security Key for JWT 
jwt.secret=FouriseDoctorAppSuperSecretKeyForSecurityDoNotShare
jwt.expiration=86400000
